<div class="row">
    <div class="col-xs-6">
        <div class="form-group">[text* your-name placeholder class:form-control "Adınız Soyadınız"]</div>
    </div>
    <div class="col-xs-6">
        <div class="form-group">[email* your-email placeholder class:form-control "E-Posta Adresiniz"]</div>
    </div>
    <div class="col-xs-12">
        <div class="form-group">[text* your-subject class:form-control placeholder "Mesaj Konusu"]
        </div>
    </div>
    <div class="col-xs-12">
        <div class="form-group">[textarea* your-message class:form-control placeholder "Mesajınız"]</div>
    </div>
    <div class="col-xs-6"><span class="note">* Zorunlu Alanlar</span></div>
    <div class="col-xs-6 text-right">[submit class:btn class:btn-primary class:send "Mesajı Gönder"]</div>
</div>

<div class="row">
    <div class="col-xs-6">
        <div class="form-group">
            <input class="form-control" placeholder="Adınız Soyadınız *" type="text">
        </div>
    </div>
    <div class="col-xs-6">
        <div class="form-group">
            <input class="form-control" placeholder="E-Posta Adresiniz *" type="email">
        </div>
    </div>
    <div class="col-xs-12">
        <div class="form-group">
            <input class="form-control" placeholder="Mesaj Konusu *" type="text">
        </div>
    </div>
    <div class="col-xs-12">
        <div class="form-group">
            <textarea class="form-control" rows="7" placeholder="Mesajınız *"></textarea>
        </div>
    </div>
    <div class="col-xs-6">
        <span class="note">* Zorunlu Alanlar</span>
    </div>
    <div class="col-xs-6 text-right">
        <button class="btn btn-primary send">Mesajı Gönder</button>
    </div>
</div>