<?php $veri = $this->kveri; ?>
<div class="col-md-8 col-sm-8 col-xs-8">
    <div class="form-group">
        <label class="form-label">Your Name</label>
        <span class="help">e.g. "Mona Lisa Portrait"</span>

        <div class="controls">
            <input class="form-control" type="text" value="<?php echo $veri['magaza_adi']; ?>">
        </div>
    </div>
    <div class="form-group">
        <label class="form-label">Password</label>
        <span class="help">e.g. "Mona Lisa Portrait"</span>

        <div class="controls">
            <input class="form-control" type="password">
        </div>
    </div>
    <div class="form-group">
        <label class="form-label">Email</label>
        <span class="help">e.g. "some@example.com"</span>

        <div class="controls">
            <input class="form-control" type="text" value="<?php echo $veri['magaza_adi']; ?>">
        </div>
    </div>
    <div class="form-group">
        <label class="form-label">Placeholder</label>
        <span class="help">e.g. "some@example.com"</span>

        <div class="controls">
            <input placeholder="You can put anything here" class="form-control" type="text"
                   value="<?php echo $veri['magaza_adi']; ?>">
        </div>
    </div>
    <div class="form-group">
        <label class="form-label">Disabled</label>
        <span class="help">e.g. "some@example.com"</span>

        <div class="controls">
            <input placeholder="You can put anything here" class="form-control" disabled="disabled" type="text">
        </div>
    </div>
</div>
