<?php $veri = $this->veriler; ?>
<!-- FORM -->

<link href="<?php echo $this->baseUrl; ?>assets/plugins/bootstrap-tag/bootstrap-tagsinput.css" rel="stylesheet"
      type="text/css"/>
<form id="commentForm" action="/urun/ekle" method="post">
    <!-- Main wrapper -->
    <div id="rootwizard" class="span12">
        <!-- Step List -->
        <div class="form-wizard-steps">
            <ul class="wizard-steps">
                <li class="" data-target="#step1"><a href="#tab1" data-toggle="tab"> <span class="step">1</span>
                        <span class="title">Ürün Bilgileri</span> </a></li>
                <li data-target="#step2" class=""><a href="#tab2" data-toggle="tab"> <span class="step">2</span>
                        <span class="title">Ürün Hakkında</span> </a></li>
                <li data-target="#step3" class=""><a href="#tab3" data-toggle="tab"> <span class="step">3</span>
                        <span class="title">Varyantasyon</span> </a></li>
                <li data-target="#step4" class=""><a href="#tab4" data-toggle="tab"> <span class="step">4</span>
			<span class="title">Son
                       </span> </a></li>
            </ul>
            <div class="clearfix"></div>
            <br>
        </div>
        <div class="tab-content transparent">
            <!-- Step -->
            <div class="tab-pane active" id="tab1">
                <div class="row form-row">
                    <div class="col-md-6">
                        <input placeholder="Ürün Adı" class="form-control no-boarder " name="txtad" id="txtad"
                               type="text">
                    </div>
                    <div class="col-md-6">
                        <input placeholder="Ürün Fiyatı" class="form-control no-boarder " name="txtfiyat" id="txtfiyati"
                               type="text">
                    </div>
                </div>
                <ul class=" wizard wizard-actions">
                    <li class="previous first disabled" style="display:none;"><a href="javascript:;" class="btn">&nbsp;&nbsp;İlk&nbsp;&nbsp;</a>
                    </li>
                    <li class="previous disabled"><a href="javascript:;" class="btn">&nbsp;&nbsp;Geri&nbsp;&nbsp;</a>
                    </li>
                    <li class="next last" style="display:none;"><a href="javascript:;" class="btn btn-primary">&nbsp;&nbsp;Son&nbsp;&nbsp;</a>
                    </li>
                    <li class="next"><a href="javascript:;" class="btn btn-primary">&nbsp;&nbsp;İleri&nbsp;&nbsp;</a>
                    </li>
                </ul>
            </div>
            <!-- Step -->
            <div class="tab-pane" id="tab2">
                <div class="row-fluid">
                    <label>Taglar</label>
                    <input class="span12 tagsinput" name="txttags" type="text"
                           value="<?php echo $tags = implode(",", $veri['tags']); ?>" data-role="tagsinput"/>
                    <label>Açıklama</label>
                    <textarea class="form-control" name="txtaciklama" rows="3"></textarea><br>
                </div>
                <ul class=" wizard wizard-actions">
                    <li class="previous first disabled" style="display:none;"><a href="javascript:;" class="btn">&nbsp;&nbsp;İlk&nbsp;&nbsp;</a>
                    </li>
                    <li class="previous disabled"><a href="javascript:;" class="btn">&nbsp;&nbsp;Geri&nbsp;&nbsp;</a>
                    </li>
                    <li class="next last" style="display:none;"><a href="javascript:;" class="btn btn-primary">&nbsp;&nbsp;Son&nbsp;&nbsp;</a>
                    </li>
                    <li class="next"><a href="javascript:;" class="btn btn-primary">&nbsp;&nbsp;İleri&nbsp;&nbsp;</a>
                    </li>
                </ul>
            </div>
            <div class="tab-pane" id="tab3">
                <span> Bu Alan henüz aktif değildir. </span>
                <ul class=" wizard wizard-actions">
                    <li class="previous first disabled" style="display:none;"><a href="javascript:;" class="btn">&nbsp;&nbsp;İlk&nbsp;&nbsp;</a>
                    </li>
                    <li class="previous disabled"><a href="javascript:;" class="btn">&nbsp;&nbsp;Geri&nbsp;&nbsp;</a>
                    </li>
                    <li class="next last" style="display:none;"><a href="javascript:;" class="btn btn-primary">&nbsp;&nbsp;Son&nbsp;&nbsp;</a>
                    </li>
                    <li class="next"><a href="javascript:;" class="btn btn-primary">&nbsp;&nbsp;İleri&nbsp;&nbsp;</a>
                    </li>
                </ul>
            </div>
            <div class="tab-pane" id="tab4">
                <input type="text" name="txtimg" value="<?php echo $veri['images']->standard_resolution->url; ?>"
                       hidden/>
                <input type="text" name="txtinstaid" value="<?php echo $veri['id']; ?>" hidden/>
                <button type="submit" class="btn btn-success btn-cons"><i class="icon-ok"></i> Ürün Oluştur.</button>
            </div>


        </div>

    </div>
</form>
<script src="<?php echo $this->baseUrl; ?>assets/plugins/bootstrap-select2/select2.min.js"
        type="text/javascript"></script>
<script src="<?php echo $this->baseUrl; ?>assets/plugins/boostrap-form-wizard/js/jquery.bootstrap.wizard.min.js"
        type="text/javascript"></script>
<script src="<?php echo $this->baseUrl; ?>assets/plugins/jquery-validation/js/jquery.validate.min.js"
        type="text/javascript"></script>
<script src="<?php echo $this->baseUrl; ?>assets/js/form_validations.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl; ?>assets/plugins/bootstrap-tag/bootstrap-tagsinput.min.js"
        type="text/javascript"></script>


