<?php
$atts = extract(shortcode_atts(array(
    'title' => __('Carousel Haberler', 'ss_framework'),
    'limit' => 9,
    'categories' => 1,
    'auto' => 0,
    'scroll_count' => ''), $atts));
$args = array('posts_per_page' => esc_attr($limit),
    'post_type' => 'post'
);
if ($categories)
    $args = array_merge($args, array('cat' => esc_attr($categories)));
query_posts($args);
$counter = 0;
if (have_posts()):
    while (have_posts()): the_post();
        if ($counter == 0) {
            echo '<li><div class="row">';
        } elseif ($counter == 3) {
            echo '</div></li><li><div class="row">';
        } elseif ($counter == 6) {
            echo '</div></li><li><div class="row">';
        }
        if (has_post_thumbnail()) {
            $image = wp_get_attachment_image_src(get_post_thumbnail_id($post->ID), 'carousel-haber');
        } else {
            $image[0] = get_template_directory_uri() . '/timthumb.php?src=' . get_template_directory_uri() . '/img/thumbnail.png&w=260&h=166';
        }
        ?>
        <div class="col-xs-4">
            <h3><a href="http://international.bahcesehir.edu.tr/exchange/"><?php echo get_the_title($post_id); ?></a>
            </h3>

            <p>
                <a href="http://international.bahcesehir.edu.tr/exchange/"><?php echo resimsiz_haber(get_the_content()); ?></a>
            </p>
        </div>
        <?php
        $counter++;
    endwhile;
    echo '</div></li>';
endif;
?>